---
root: true

env:
  browser: true
  es2021: true
  node: true
extends:
  - prettier
  - 'prettier/react'
  - 'plugin:@next/next/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - "generated-types.ts"
rules:
  no-unused-vars: error
  '@next/next/no-img-element': 0
