/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/likes": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.likes.id"];
          slug?: parameters["rowFilter.likes.slug"];
          ip?: parameters["rowFilter.likes.ip"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["likes"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** likes */
          likes?: definitions["likes"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.likes.id"];
          slug?: parameters["rowFilter.likes.slug"];
          ip?: parameters["rowFilter.likes.ip"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.likes.id"];
          slug?: parameters["rowFilter.likes.slug"];
          ip?: parameters["rowFilter.likes.ip"];
        };
        body: {
          /** likes */
          likes?: definitions["likes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/translation_requests": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.translation_requests.id"];
          slug?: parameters["rowFilter.translation_requests.slug"];
          ip?: parameters["rowFilter.translation_requests.ip"];
          inserted_at?: parameters["rowFilter.translation_requests.inserted_at"];
          guessed_country?: parameters["rowFilter.translation_requests.guessed_country"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["translation_requests"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** translation_requests */
          translation_requests?: definitions["translation_requests"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.translation_requests.id"];
          slug?: parameters["rowFilter.translation_requests.slug"];
          ip?: parameters["rowFilter.translation_requests.ip"];
          inserted_at?: parameters["rowFilter.translation_requests.inserted_at"];
          guessed_country?: parameters["rowFilter.translation_requests.guessed_country"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.translation_requests.id"];
          slug?: parameters["rowFilter.translation_requests.slug"];
          ip?: parameters["rowFilter.translation_requests.ip"];
          inserted_at?: parameters["rowFilter.translation_requests.inserted_at"];
          guessed_country?: parameters["rowFilter.translation_requests.guessed_country"];
        };
        body: {
          /** translation_requests */
          translation_requests?: definitions["translation_requests"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  likes: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    slug?: string;
    ip?: string;
  };
  translation_requests: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    slug?: string;
    ip?: string;
    inserted_at?: string;
    guessed_country?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** likes */
  "body.likes": definitions["likes"];
  "rowFilter.likes.id": string;
  "rowFilter.likes.slug": string;
  "rowFilter.likes.ip": string;
  /** translation_requests */
  "body.translation_requests": definitions["translation_requests"];
  "rowFilter.translation_requests.id": string;
  "rowFilter.translation_requests.slug": string;
  "rowFilter.translation_requests.ip": string;
  "rowFilter.translation_requests.inserted_at": string;
  "rowFilter.translation_requests.guessed_country": string;
}

export interface operations {}

export interface external {}
