name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_SERVER_INIT_PATH: ${{ secrets.SENTRY_SERVER_INIT_PATH }}
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      STORYBLOK_API_TOKEN: ${{ secrets.STORYBLOK_API_TOKEN }}
      UNSPLASH_ACCESS_TOKEN: ${{ secrets.UNSPLASH_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with: version: 6
        run_install: |
          - recursive: true
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: pnpm install
          build: pnpm run build
          start: pnpm start
