name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with: version: 6
        run_install: |
          - recursive: true
      - run: pnpm install
      - run: pnpm run lint
